import React from "react";
import { Link } from "react-router-dom";

const Solar = () => {
  return (
    <div className="w-full">

      {/* ================= HERO BANNER ================= */}
      <section className="relative w-full h-[40vh] flex items-center justify-center">
        <img
          src="/solar2.webp"
          alt="Solar System Installation"
          className="absolute inset-0 w-full h-full object-cover"
        />

        <div className="absolute inset-0 bg-black/40"></div>

        <div className="relative text-center text-white px-4">
          <h1 className="text-3xl md:text-4xl font-bold mb-3">
            Solar System Installation
          </h1>

          <p className="text-sm md:text-lg">
            <Link to="/" className="hover:text-orange-400">
              Home
            </Link>{" "}
            &gt;&gt; Solar System Installation
          </p>
        </div>
      </section>

      {/* ================= MAIN CONTENT ================= */}
      <section className="py-16 bg-white">
        <div className="max-w-7xl mx-auto px-6 grid lg:grid-cols-3 gap-12">

          {/* ================= LEFT CONTENT ================= */}
          <div className="lg:col-span-2">

            {/* Main Image */}
            <img
              src="/solar2.jpg"
              alt="Solar Panel Installation"
              className="rounded-lg mb-8 w-full h-[450px]"
            />

            {/* Title */}
            <h2 className="text-3xl font-bold mb-5">
              Solar System Installation
            </h2>

            {/* Paragraph */}
            <p className="text-gray-600 leading-relaxed mb-6">
              Solar system installation involves setting up photovoltaic
              (PV) panels and related electrical components to generate
              electricity using sunlight. Solar energy systems are widely
              used in residential homes, commercial buildings, industrial
              facilities, and agricultural properties to reduce electricity
              costs and promote sustainable energy use. A properly designed
              solar system converts sunlight into usable electrical energy
              that can power lighting, appliances, and other electrical
              equipment.
            </p>

            <p className="text-gray-600 leading-relaxed mb-8">
              The installation process begins with site assessment and
              energy requirement analysis. Engineers evaluate roof space,
              sunlight exposure, and energy consumption patterns to design
              the most efficient solar power system. Based on these
              calculations, solar panels, inverters, mounting structures,
              and electrical wiring systems are selected to ensure optimal
              energy generation and performance.
            </p>

            {/* ================= HEADING ================= */}
            <h3 className="text-2xl font-semibold mb-6">
              Solar Panel Integration & Energy Management
            </h3>

            

            {/* More Info */}
            <p className="text-gray-600 leading-relaxed mb-6">
              During installation, solar panels are mounted on rooftops
              or ground-mounted structures at angles that maximize sunlight
              absorption throughout the day. Electrical wiring connects the
              panels to solar inverters, which convert the generated direct
              current (DC) electricity into alternating current (AC)
              suitable for powering buildings and electrical equipment.
              Proper installation ensures safe and efficient energy
              conversion.
            </p>

            <p className="text-gray-600 leading-relaxed mb-6">
              Modern solar systems may also include energy storage
              batteries, smart energy monitoring systems, and grid-tied
              connections. Grid-connected systems allow excess electricity
              generated by solar panels to be sent back to the utility grid,
              helping reduce electricity bills and improve energy
              efficiency. These systems provide reliable power while
              supporting environmentally friendly energy practices.
            </p>

            <p className="text-gray-600 leading-relaxed">
              Safety and system efficiency are essential aspects of solar
              installation. Professional installers ensure proper grounding,
              surge protection, and electrical safety compliance. After
              installation, the entire solar system is tested to verify
              performance, voltage stability, and energy output. A
              professionally installed solar energy system provides
              long-term savings, reduces carbon footprint, and offers a
              sustainable source of electricity for homes and businesses.
            </p>

          </div>

          {/* ================= RIGHT SIDEBAR ================= */}
          <div>
            <div className="bg-gray-100 p-8 rounded-lg">

              <h3 className="text-xl font-bold mb-6 border-b pb-3">
                Electrical Services
              </h3>

              <ul className="space-y-4 text-gray-700">

                <li>
                  <Link to="/commercial-electrical-installation" className="hover:text-orange-500">
                    ▸ Commercial Electrical Installation
                  </Link>
                </li>

                <li>
                  <Link to="/industrial-electrical-installation" className="hover:text-orange-500">
                    ▸ Industrial Electrical Installation
                  </Link>
                </li>

                <li>
                  <Link to="/farmhouse-electrical-installation" className="hover:text-orange-500">
                    ▸ Farmhouse Electrical Installation
                  </Link>
                </li>

                <li>
                  <Link to="/electrical-turnkey-projects" className="hover:text-orange-500">
                    ▸ Electrical Turnkey Projects
                  </Link>
                </li>

                <li>
                  <Link to="/ht-lt-cable-laying" className="hover:text-orange-500">
                    ▸ HT-LT Cable Laying
                  </Link>
                </li>

                <li>
                  <Link to="/solar-system-installation" className="hover:text-orange-500">
                    ▸ Solar System Installation
                  </Link>
                </li>

                <li>
                  <Link to="/lighting-contractors" className="hover:text-orange-500">
                    ▸ Lighting Contractors
                  </Link>
                </li>

                <li>
                  <Link to="/commercial-electrical-works" className="hover:text-orange-500">
                    ▸ Commercial Electrical Works
                  </Link>
                </li>

                <li>
                  <Link to="/residential-electrical-work" className="hover:text-orange-500">
                    ▸ Residential Electrical Work
                  </Link>
                </li>

              </ul>

            </div>
          </div>

        </div>
      </section>

    </div>
  );
};

export default Solar;